### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by cyberfly79** [alextud/ha-prana#1]
Hi,
I also have a recuperator (prana-150, not premium) (no sensors). The ios app partially works. I tried your component.
in app only these features are available:
 - power on/off
 - speed setting (speed list: 1-10) (in out and together)
 - winter mode can be switched (thaw_on)
 - heater mode can be switched (heater_on)
 - off timer
 - display brightness

your program handles it well:
 - speed query
 - speed_in query
 - speed_out query
 - speed_in&out query (I do not fully understand this, it gives a value)
 - winter mode query (thaw_on)
 - heating mode query (heater_on)

it does not exist
 - co2
 - voc
 - direction
 - auto_mode
 - night_mode
 - air_in
 - air_out

(night mode = speed 1 (low)) (not a separate mode)
(auto mode cannot be switched - or I couldn't find a way :)) because of this: speed_list: off, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

Unfortunately I failed to control, the server is far enough away from the recuperator and I get quite a few communication errors. I'm trying to bridge the problem somehow. Don't have an idea to extend bluetooth?

Thanks,

Laszlo

**Comment by cyberfly79** [comment]
I installed a raspberry pi and installed the latest home assistant (in docker). Queries, speed adjustment, shutdown also work fine. Unfortunately, turning on doesn't work.
How can special modes be activated? (heating, winter mode)

**Comment by alextud** [comment]
for heater / winter mode we can expose them as separate switch, do you need them ?

**Comment by cyberfly79** [comment]
I think somehow it would be nice to handle these features as well

**Comment by cyberfly79** [comment]
I've been using it for a long time and it works almost perfectly. The power on function is missing, unfortunately it doesn't work.

**Comment by alextud** [comment]
I've found the powerOn command, it should work now.

**Comment by cyberfly79** [comment]
Yes, super, it works. Thanks!
